const DB=[
["egg","Eggs",1,"piece",72,6.3,.4,4.8,0,.7,"nonveg"],["eggs","Eggs",1,"piece",72,6.3,.4,4.8,0,.7,"nonveg"],["chicken","Chicken breast",100,"g",165,31,0,3.6,0,.65,"nonveg"],["chicken breast","Chicken breast",100,"g",165,31,0,3.6,0,.65,"nonveg"],["fish","Fish",100,"g",140,26,0,4,0,.9,"nonveg"],["soy","Soy chunks",100,"g",345,52,33,.5,13,.15,"veg"],["soya","Soy chunks",100,"g",345,52,33,.5,13,.15,"veg"],["soy chunks","Soy chunks",100,"g",345,52,33,.5,13,.15,"veg"],["paneer","Paneer",100,"g",265,18,6,20,0,.45,"veg"],["tofu","Tofu",100,"g",145,17,2,9,1,.3,"veg"],["milk","Milk",250,"ml",153,8,12,8.3,0,.18,"veg"],["curd","Curd",100,"g",61,3.5,4.7,3.3,0,.08,"veg"],["yogurt","Curd",100,"g",61,3.5,4.7,3.3,0,.08,"veg"],["moong dal","Moong dal",100,"g",347,24,63,1.2,16,.14,"veg"],["masoor dal","Masoor dal",100,"g",352,25,63,1.1,11,.12,"veg"],["dal","Dal",100,"g",350,23,62,2,14,.14,"veg"],["chana","Chickpeas",100,"g",364,19,61,6,17,.13,"veg"],["rajma","Rajma",100,"g",333,24,60,1.2,25,.14,"veg"],["roasted chana","Roasted chana",100,"g",360,20,60,6,15,.16,"veg"],["peanuts","Peanuts",100,"g",567,26,16,49,9,.18,"veg"],["oats","Oats",100,"g",389,17,66,7,11,.18,"veg"],["rice","Rice",150,"g",195,4,42,.5,.6,.11,"veg"],["roti","Roti",1,"piece",110,3.5,22,1.5,3,3,"veg"],["chapati","Roti",1,"piece",110,3.5,22,1.5,3,3,"veg"],["idli","Idli",2,"piece",120,4,25,.5,1.5,10,"veg"],["dosa","Dosa",1,"piece",170,4,25,6,1.5,15,"veg"],["banana","Banana",1,"piece",105,1.3,27,.4,3,6,"veg"],["apple","Apple",1,"piece",95,.5,25,.3,4.4,20,"veg"],["whey","Whey protein",30,"g",120,24,3,2,0,45,"veg"],["protein powder","Whey protein",30,"g",120,24,3,2,0,45,"veg"],["bread","Bread",2,"piece",140,6,26,2,2,8,"veg"],["sambar","Sambar",200,"ml",130,6,18,3,5,15,"veg"]];
const WORK={
0:{name:"Recovery / Mobility",focus:"Recovery",time:"20–30 min",ex:[["Walking","Treadmill","20–30 min","Easy pace"],["Hip & shoulder mobility","Bodyweight","2×8 each","Controlled"]]},
1:{name:"Chest + Triceps",focus:"Push",time:"45–60 min",ex:[["Barbell Bench Press","Barbell + Bench","3×6–10","2–3 min"],["Incline Dumbbell Press","Dumbbells + Incline Bench","3×8–12","90 sec"],["Cable Chest Fly","Cable Machine","3×10–15","60–90 sec"],["Triceps Pushdown","Cable Machine","3×10–15","60–90 sec"],["Overhead Triceps Extension","Cable/Dumbbell","2×10–15","60–90 sec"]]},
2:{name:"Back + Biceps",focus:"Pull",time:"45–60 min",ex:[["Lat Pulldown","Lat Pulldown Machine","3×8–12","90 sec"],["Seated Cable Row","Cable Machine","3×8–12","90 sec"],["One-Arm Dumbbell Row","Dumbbell + Bench","3×8–12/side","90 sec"],["Dumbbell Curl","Dumbbells","3×10–12","60 sec"],["Hammer Curl","Dumbbells","2×10–15","60 sec"]]},
3:{name:"Legs",focus:"Lower body",time:"50–65 min",ex:[["Squat","Barbell + Rack","3×6–10","2–3 min"],["Leg Press","Leg Press Machine","3×10–12","2 min"],["Romanian Deadlift","Barbell/Dumbbells","3×8–12","2 min"],["Leg Curl","Leg Curl Machine","3×10–15","90 sec"],["Standing Calf Raise","Calf Machine","3×12–20","60 sec"]]},
4:{name:"Shoulders + Core",focus:"Delts + Core",time:"40–55 min",ex:[["Seated Dumbbell Shoulder Press","Dumbbells + Bench","3×8–12","90 sec"],["Lateral Raise","Dumbbells/Cable","3×12–15","60 sec"],["Rear Delt Fly","Reverse Pec Deck","3×12–15","60 sec"],["Cable Face Pull","Cable Machine","2×12–15","60 sec"],["Cable Crunch","Cable Machine","3×10–15","60 sec"]]},
5:{name:"Upper Body",focus:"Chest + Back + Arms",time:"45–60 min",ex:[["Incline Bench Press","Barbell/Dumbbells + Bench","3×8–10","2 min"],["Lat Pulldown","Lat Pulldown Machine","3×8–12","90 sec"],["Cable Row","Cable Machine","3×8–12","90 sec"],["Lateral Raise","Dumbbells/Cable","2×12–15","60 sec"],["Cable Triceps Pushdown","Cable Machine","2×10–15","60 sec"]]},
6:{name:"Active Recovery",focus:"Recovery",time:"20–30 min",ex:[["Cycling","Stationary Bike","20 min","Easy/moderate"],["Full-body mobility","Bodyweight","10 min","Controlled"]]}
};
const S=JSON.parse(localStorage.getItem("ppcomplete")||"{}");S.logs=S.logs||{};S.settings=S.settings||{p:120,c:2400,b:3000,level:"beginner"};S.done=S.done||{};
const key=()=>new Date().toISOString().slice(0,10),vegDay=()=>[2,6].includes(new Date().getDay());
function findFood(n){n=n.toLowerCase().trim();return DB.find(x=>x[0]===n)||DB.find(x=>n.includes(x[0]))}
function parse(txt){return txt.split(/\s*(?:,|\+|\band\b)\s*/i).map(part=>{let m=part.match(/([\d.]+)\s*(kg|g|grams?|ml|litres?|l|pieces?|pcs)?\s*(.*)/i),q,u,n;if(m){q=+m[1];u=(m[2]||"").toLowerCase();n=m[3]}else n=part;let f=findFood(n);if(!f)return null;if(q==null){q=f[2];u=f[3]}if(u==="kg")q*=100,u="g";if(u==="l"||u==="litre"||u==="litres")q*=1000,u="ml";return {f,qty:q}}).filter(Boolean)}
function totals(arr=S.logs[key()]||[]){return arr.reduce((a,x)=>{let f=x.f,k=x.qty/f[2];a.p+=f[5]*k;a.cal+=f[4]*k;a.carb+=f[6]*k;a.fat+=f[7]*k;a.fiber+=f[8]*k;a.cost+=f[9]*k;return a},{p:0,cal:0,carb:0,fat:0,fiber:0,cost:0})}
function save(){localStorage.setItem("ppcomplete",JSON.stringify(S))}
function render(){
 let t=totals(),v=vegDay(),w=WORK[new Date().getDay()];dayBadge.className="badge "+(v?"veg":"nonveg");dayBadge.textContent=v?"🌱 STRICT VEG DAY — NO EGGS":"🍗 NON-VEG ALLOWED";date.textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});dayRule.textContent=v?"Tuesday and Saturday: vegetarian foods only. Eggs, chicken and fish are blocked.":"All foods are available.";
 proteinTarget.value=S.settings.p;calorieTarget.value=S.settings.c;budget.value=S.settings.b;level.value=S.settings.level;p.textContent=t.p.toFixed(1)+"g";cal.textContent=Math.round(t.cal)+" kcal";carb.textContent=t.carb.toFixed(1)+"g";fat.textContent=t.fat.toFixed(1)+"g";fiber.textContent=t.fiber.toFixed(1)+"g";cost.textContent="₹"+t.cost.toFixed(0);pRemain.textContent=t.p<S.settings.p?`${(S.settings.p-t.p).toFixed(0)}g remaining`:"Target reached";calRemain.textContent=t.cal<S.settings.c?`${Math.round(S.settings.c-t.cal)} kcal left`:"Target reached";pBar.style.width=Math.min(100,t.p/S.settings.p*100)+"%";calBar.style.width=Math.min(100,t.cal/S.settings.c*100)+"%";
 renderLog();renderWorkout(w);renderSuggestions(t,v);renderBudget()
}
function renderLog(){let a=S.logs[key()]||[];log.innerHTML=a.length?a.map((x,i)=>`<div class="food"><div><b>${x.f[1]}</b><small>${x.qty}${x.f[3]} • ${x.meal}</small></div><span>${(x.f[5]*x.qty/x.f[2]).toFixed(1)}g P<br>${Math.round(x.f[4]*x.qty/x.f[2])} kcal</span><button class="remove" onclick="del(${i})">✕</button></div>`).join(""):"<p class='muted'>Nothing logged yet.</p>"}
function del(i){S.logs[key()].splice(i,1);save();render()}
function renderWorkout(w){let done=S.done[key()]||[];workoutName.textContent=w.name;workoutMeta.textContent=w.focus+" • "+w.time;workoutProgress.textContent=`${done.length}/${w.ex.length} done`;exerciseList.innerHTML=w.ex.map((e,i)=>{let d=done.includes(i);return `<div class="exercise ${d?"done":""}"><input type="checkbox" ${d?"checked":""} onchange="toggleEx(${i})"><div><b>${e[0]}</b><small>🏋️ ${e[1]} • ${e[2]}</small></div><div class="tag">Rest<br>${e[3]}</div></div>`}).join("")}
function toggleEx(i){S.done[key()]=S.done[key()]||[];let a=S.done[key()],n=a.indexOf(i);n>=0?a.splice(n,1):a.push(i);save();render()}
function renderSuggestions(t,v){let need=Math.max(0,S.settings.p-t.p);if(!need){suggestions.innerHTML="<div class='suggest'><b>🔥 Protein target achieved.</b> Keep meals balanced.</div>";return}let a=DB.filter((f,i)=>i===DB.findIndex(z=>z[1]===f[1])).filter(f=>!v||f[10]==="veg").sort((x,y)=>(y[5]/y[9])-(x[5]/x[9]));suggestions.innerHTML=`<p>You need about <b>${need.toFixed(0)}g protein</b> more today.</p>`+a.slice(0,6).map(f=>{let q=Math.ceil(need/f[5]*f[2]/10)*10;return `<div class="suggest"><b>${f[1]}</b> — ${q}${f[3]} → ~${(f[5]*q/f[2]).toFixed(0)}g protein • ~₹${(f[9]*q/f[2]).toFixed(0)}</div>`}).join("")}
function renderBudget(){let spent=Object.values(S.logs).reduce((a,x)=>a+totals(x).cost,0);spentEl.textContent="₹"+spent.toFixed(0);remaining.textContent="₹"+(S.settings.b-spent).toFixed(0);budgetBar.style.width=Math.min(100,spent/S.settings.b*100)+"%"}
add.onclick=()=>{let a=parse(foodInput.value);if(!a.length){parsePreview.innerHTML="<div class='preview warning'>Try: “3 eggs, 250ml milk, 100g paneer”.</div>";return}let blocked=a.filter(x=>vegDay()&&x.f[10]!=="veg");if(blocked){if(blocked.length){parsePreview.innerHTML=`<div class="preview warning">🚫 ${blocked.map(x=>x.f[1]).join(", ")} is not allowed today. Tuesday and Saturday are strict vegetarian days, including no eggs.</div>`;return}}S.logs[key()]??=[];a.forEach(x=>S.logs[key()].push({f:x.f,qty:x.qty,meal:meal.value}));save();foodInput.value="";parsePreview.innerHTML="<div class='preview ok'>✓ Added and calculated.</div>";render()};
foodInput.oninput=()=>{let a=parse(foodInput.value);parsePreview.innerHTML=a.length?`<div class="preview">${a.map(x=>`${x.f[1]} × ${x.qty}${x.f[3]}`).join(" • ")}</div>`:""};
document.querySelectorAll(".chips button").forEach(b=>b.onclick=()=>{foodInput.value=b.textContent;foodInput.dispatchEvent(new Event("input"))});
[proteinTarget,calorieTarget,budget].forEach((e,i)=>e.onchange=()=>{S.settings[i===0?"p":i===1?"c":"b"]=+e.value||0;save();render()});level.onchange=()=>{S.settings.level=level.value;save();render()};
theme.onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("ppdark",document.body.classList.contains("dark"))};if(localStorage.getItem("ppdark")==="true")document.body.classList.add("dark");
document.getElementById("export").onclick=()=>{let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:"application/json"}));a.download="proteinpilot-backup.json";a.click()};
document.getElementById("import").onchange=e=>{let r=new FileReader();r.onload=()=>{try{localStorage.setItem("ppcomplete",r.result);location.reload()}catch{alert("Invalid backup")}};r.readAsText(e.target.files[0])};
document.getElementById("reset").onclick=()=>{if(confirm("Delete all food and workout data?")){localStorage.removeItem("ppcomplete");location.reload()}};render();